### ISSUE TITLE
Tick labels on bar chart

### ISSUE THREAD

**Issue by ZenVega** [technologiestiftung/innovationserhebung#30]
There is an issue with the tick labels for the bar chart. On every reload, the labels are rendered a little differently. like this: 
<img width="946" alt="image" src="https://github.com/technologiestiftung/innovationserhebung/assets/50147356/3b686715-54c3-4ed3-99ec-9d415e769038">
<img width="933" alt="image" src="https://github.com/technologiestiftung/innovationserhebung/assets/50147356/045a3211-7c36-4569-80fb-9ae379c65147">
<img width="944" alt="image" src="https://github.com/technologiestiftung/innovationserhebung/assets/50147356/29bcf6be-6a24-49c2-969a-8cd3eadea273">
It is also a little strange behaviour, that bokeh includes linebreaks fo "/" but not for spaces. Therefore a label like:
"Nahrung/Getränke/Tabak", becomes
Nahrung/
Getränke/
Tabak",

how ever "Forschung und Entwicklung",
stays as it is.
I wonder if we should use an external legend here instead of tick labels, that would also solve the problem with responsiveness.

@guadiromero @herrherrmann

**Comment by ZenVega** [comment]
Ah, I guess the lineheight is just insanely high.. therefore the groups get mixed up

**Comment by guadiromero** [comment]
@ZenVega Perfect, thanks Urs!

Regarding the line breaks, this was done by me in Python, and I can customize it as we wish :)

**Comment by ZenVega** [comment]
Ah, I see. Great! Then I guess we should discuss the use of a legend with macro. I included the line height fix already in the new PR #31
