### ISSUE TITLE
Remove hyphenation from nav

### ISSUE THREAD

**Issue by ZenVega** [technologiestiftung/innovationserhebung#48]
To @marcoka2000 . I feel we should remove hyphenation in the navigation since we're anyway going multiline here: 
<img width="391" alt="image" src="https://github.com/technologiestiftung/innovationserhebung/assets/50147356/fc1809ec-c6d9-407f-80c4-a8d623e31181">

What's your opinion on that?

**Comment by marcoka2000** [comment]
@ZenVega Like discussed last week: yes, go for it 💪

**Comment by MRigal** [comment]
We actually fixed that
